# Generated by Django 5.0 on 2023-12-07 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ArchDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=30)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('arch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='catalog.arch')),
            ],
        ),
        migrations.CreateModel(
            name='ArchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='arch_image/')),
                ('arch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='catalog.arch')),
            ],
        ),
        migrations.CreateModel(
            name='SimilarProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='similar_product_image/')),
                ('arch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_product', to='catalog.arch')),
            ],
        ),
    ]
