# Generated by Django 5.0 on 2023-12-11 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='archdetails',
            name='arch',
        ),
        migrations.RemoveField(
            model_name='similarproduct',
            name='arch',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('articl', models.CharField(max_length=30)),
                ('width', models.CharField(max_length=30)),
                ('height', models.CharField(max_length=30)),
                ('depth', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='product_image/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_image/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='catalog.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ArchImage',
        ),
        migrations.DeleteModel(
            name='ArchDetails',
        ),
        migrations.DeleteModel(
            name='Arch',
        ),
        migrations.DeleteModel(
            name='SimilarProduct',
        ),
    ]
